### ISSUE TITLE
Running from Mac

### ISSUE THREAD

**Issue by uhlhosting** [chippawah/proxmox-cluster-example#1]
Hi,

I got this, while trying to run it from my mac against our proxmox cluster.

```
module.talos.proxmox_vm_qemu.talos-control-plane-node[1]: Creating...
module.talos.proxmox_vm_qemu.talos-worker-node[2]: Creating...
module.talos.proxmox_vm_qemu.talos-control-plane-node[2]: Creating...
module.talos.proxmox_vm_qemu.talos-worker-node[0]: Creating...
module.talos.proxmox_vm_qemu.talos-control-plane-node[0]: Creating...
module.talos.proxmox_vm_qemu.talos-worker-node[3]: Creating...
module.talos.proxmox_vm_qemu.talos-worker-node[4]: Creating...
module.talos.proxmox_vm_qemu.talos-worker-node[1]: Creating...
module.talos.proxmox_vm_qemu.talos-worker-node[2]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-control-plane-node[1]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-control-plane-node[2]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-worker-node[0]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-control-plane-node[0]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-worker-node[3]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-worker-node[4]: Still creating... [10s elapsed]
module.talos.proxmox_vm_qemu.talos-worker-node[1]: Still creating... [10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-control-plane-node[0],
│   on talos/control_plane_node.tf line 1, in resource "proxmox_vm_qemu" "talos-control-plane-node":
│    1: resource "proxmox_vm_qemu" "talos-control-plane-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-control-plane-node[1],
│   on talos/control_plane_node.tf line 1, in resource "proxmox_vm_qemu" "talos-control-plane-node":
│    1: resource "proxmox_vm_qemu" "talos-control-plane-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-control-plane-node[2],
│   on talos/control_plane_node.tf line 1, in resource "proxmox_vm_qemu" "talos-control-plane-node":
│    1: resource "proxmox_vm_qemu" "talos-control-plane-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-worker-node[4],
│   on talos/worker_node.tf line 1, in resource "proxmox_vm_qemu" "talos-worker-node":
│    1: resource "proxmox_vm_qemu" "talos-worker-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-worker-node[3],
│   on talos/worker_node.tf line 1, in resource "proxmox_vm_qemu" "talos-worker-node":
│    1: resource "proxmox_vm_qemu" "talos-worker-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-worker-node[2],
│   on talos/worker_node.tf line 1, in resource "proxmox_vm_qemu" "talos-worker-node":
│    1: resource "proxmox_vm_qemu" "talos-worker-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-worker-node[1],
│   on talos/worker_node.tf line 1, in resource "proxmox_vm_qemu" "talos-worker-node":
│    1: resource "proxmox_vm_qemu" "talos-worker-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.3 plugin:

panic: interface conversion: interface {} is nil, not []interface {}

goroutine 148 [running]:
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefsByName(0xc00055e640, 0xc000540150, 0x15, 0x1, 0x1, 0x0, 0x0, 0xc000234400)
	github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:190 +0x845
github.com/Telmate/proxmox-api-go/proxmox.(*Client).GetVmRefByName(...)
	github.com/Telmate/proxmox-api-go@v0.0.0-20211123192920-062fd1a6ab10/proxmox/client.go:180
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0001f9e80, 0x17c53c0, 0xc0004b20f0, 0x9, 0xffffffffffffffff)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:738 +0x1886
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000448460, 0x1a0b1b8, 0xc000796440, 0xc0001f9e80, 0x17c53c0, 0xc0004b20f0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:329 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000448460, 0x1a0b1b8, 0xc000796440, 0xc0005ae270, 0xc0001f9a80, 0x17c53c0, 0xc0004b20f0, 0x0, 0x0, 0x0, ...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:467 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000c60c0, 0x1a0b1b8, 0xc000796440, 0xc000198230, 0xc000796440, 0x18d06a0, 0xc000890100)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000388bc0, 0x1a0b260, 0xc000796440, 0xc00054c000, 0xc000388bc0, 0xc000511ba0, 0x106c287)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x18d06a0, 0xc000388bc0, 0x1a0b260, 0xc000890180, 0xc0000cad20, 0x0, 0x1a0b260, 0xc000890180, 0xc0005cec80, 0xc10)
	github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e2540, 0x1a12c18, 0xc00008bb00, 0xc00058c5a0, 0xc0003827b0, 0x1e55f40, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000e2540, 0x1a12c18, 0xc00008bb00, 0xc00058c5a0, 0x0)
	google.golang.org/grpc@v1.42.0/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000341c0, 0xc0000e2540, 0x1a12c18, 0xc00008bb00, 0xc00058c5a0)
	google.golang.org/grpc@v1.42.0/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.42.0/server.go:919 +0x1fd

Error: The terraform-provider-proxmox_v2.9.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│ 
│   with module.talos.proxmox_vm_qemu.talos-worker-node[0],
│   on talos/worker_node.tf line 1, in resource "proxmox_vm_qemu" "talos-worker-node":
│    1: resource "proxmox_vm_qemu" "talos-worker-node" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

cosmic@Revenger proxmox-cluster %      
```                                                                                                                    [10:27PM]

**Comment by uhlhosting** [comment]
/api2/json was missed from URL solved.
